In [1]:
import numpy as np

A = np.matrix([
    [2,-1,0],
    [1,2,1],
    [4,1,3]
])

In [2]:
# Task 5.1

def is_square(A):
    (nrow,ncol) = A.shape
    if(nrow == ncol):
        return True
    else:
        return False
    # end if
# end func

if(is_square(A)):
    print('{} is a square matrix.'.format(A))
else:
    print('{} is not a square matrix.'.format(A))

[[ 2 -1  0]
 [ 1  2  1]
 [ 4  1  3]] is a square matrix.


In [3]:
# Task 5.2

def is_symmetric(A):
    (nrow,ncol) = A.shape
    for i in range(0,nrow):
        for j in range(0,ncol):
            if(A[i,j] == A[j,i]):
                pass
            else:
                return False
            # end if
        # end for
    # end for
    return True
# end func

if(is_symmetric(A)):
    print('{} is a symmetric matrix.'.format(A))
else:
    print('{} is not a symmetric matrix.'.format(A))

[[ 2 -1  0]
 [ 1  2  1]
 [ 4  1  3]] is not a symmetric matrix.


In [4]:
# Task 5.3

def is_diagonal(A):
    (nrow,ncol) = A.shape
    for i in range(0,nrow):
        for j in range(0,ncol):
            if((i != j) and (A[i,j] != 0)):
                return False
            else:
                pass
            # end if
        # end for
    # end for
    return True
# end func

if(is_diagonal(A)):
    print('{} is a diagonal matrix.'.format(A))
else:
    print('{} is not a diagonal matrix.'.format(A))

[[ 2 -1  0]
 [ 1  2  1]
 [ 4  1  3]] is not a diagonal matrix.


In [5]:
# Task 5.4

def is_identity(A):
    (nrow,ncol) = A.shape
    for i in range(0,nrow):
        for j in range(0,ncol):
            if((i != j) and (A[i,j] != 0)):
                return False
            elif((i == j) and (A[i,j] != 1)):
                return False
            else:
                pass
            # end if
        # end for
    # end for
    return True
# end func

if(is_identity(A)):
    print('{} is a identity matrix.'.format(A))
else:
    print('{} is not a identity matrix.'.format(A))

[[ 2 -1  0]
 [ 1  2  1]
 [ 4  1  3]] is not a identity matrix.


In [6]:
# Task 5.5

def is_zero(A):
    (nrow,ncol) = A.shape
    for i in range(0,nrow):
        for j in range(0,ncol):
            if(A[i,j] != 0):
                return False
            else:
                pass
            # end if
        # end for
    # end for
    return True
# end func

if(is_zero(A)):
    print('{} is a zero matrix.'.format(A))
else:
    print('{} is not a zero matrix.'.format(A))

[[ 2 -1  0]
 [ 1  2  1]
 [ 4  1  3]] is not a zero matrix.


In [7]:
# Task 5.6

def transpose(A):
    (nrow,ncol) = A.shape
    trans = np.empty((nrow,ncol),dtype=int)
    
    for i in range(0,nrow):
        for j in range(0,ncol):
            trans[j,i] = A[i,j]
            # end if
        # end for
    # end for
    return trans
# end func

print('the transpose of A is')
transpose(A)

the transpose of A is


array([[ 2,  1,  4],
       [-1,  2,  1],
       [ 0,  1,  3]])

In [8]:
import numpy as np

A = np.matrix([
    [1,2,3],
    [4,5,6]
])

B = np.matrix([
    [1,2],
    [3,4],
    [5,6]
])

In [9]:
# Task 6.1

def dot_product(A,B):
    (arow,acol) = A.shape
    (brow,bcol) = B.shape
    dots = np.empty((arow,bcol),dtype=int)
    if(acol == brow):
        for i in range(0,arow):
            for j in range(0,bcol):
                sum = 0
                for k in range(0,acol):
                    element = A[i,k] * B[k,j]
                    sum = sum + element
                # end for
                dots[i,j] = sum
            # end for
        # end for
        return dots
    else:
        return 'Multiplication error!'
    # end if
# end func

print('The multiplication (for) between A and B is')
dot_product(A,B)

The multiplication (for) between A and B is


array([[22, 28],
       [49, 64]])

In [10]:
# Task 6.2

def dot_product(A,B):
    (arow,acol) = A.shape
    (brow,bcol) = B.shape
    dots = np.empty((arow,bcol),dtype=int)
    if(acol == brow):
        i = 0
        while i < arow:
            j = 0
            while j < bcol:
                sum = 0
                k = 0
                while k < acol:
                    element = A[i,k] * B[k,j]
                    sum = sum + element 
                    k += 1
                # end while
                dots[i,j] = sum
                j += 1
            # end while
            i += 1
        #end while
        return dots
    else:
        return 'Multiplication error!'
    # end if
# end func

print('The multiplication (while) between A and B is')
dot_product(A,B)

The multiplication (while) between A and B is


array([[22, 28],
       [49, 64]])

In [11]:
import numpy as np

C = ([
    [1,3,2],
    [-3,-1,-3],
    [2,3,1]
])

In [12]:
# Task 7

def minor_request(A,x,y):
    mi_rqst = []
    for i in range(len(A)):
        check = []
        for j in range(len(A)):
            
            if i != y and j != x:
                check.append(A[j][i]) 
                
            # end if
        # end for
        if check:
            mi_rqst.append(check)
    # end for
    return mi_rqst
# end func

def deter33(A):
    d = 0
    if(len(A) == 1):
        d = A[0,0]
    else:
        for c in range(0,len(A)):
            m = minor_request(A,0,c)
            temp2 = (m[0][0] * m[1][1]) - (m[0][1] * m[1][0])
            d = d + (-1)**(c) * A[0][c] * temp2
        # end for
    return d  
# end func

print('the determinant of C is {}'.format(deter33(C)))

the determinant of C is -15


In [13]:
D = ([
    [1,1,-1,-2],
    [0,2,1,3],
    [0,1,1,3],
    [0,2,1,4]
])

In [14]:
# Task 8.1

def deter(A):
    d = 0
    if(len(A) == 1):
        d = A[0][0]
    else:
        for c in range(0,len(A)):
            m = minor_request(A,0,c)
            d = d + (-1)**(c) * A[0][c] * deter(m)
        # end for
    return d  
# end func

def minor(A):
    mi = []
    for i in range(len(A)):
        for j in range(len(A)):
            x = deter(minor_request(A,i,j))
            mi.append(x)
        # end for
    # end for
    return np.array(mi).reshape(len(A),len(A))
# end func

print('the minor of D is')
minor(D)

the minor of D is


array([[ 1,  0,  0,  0],
       [ 1,  1, -2, -1],
       [ 3,  1,  2,  0],
       [ 1,  0,  3,  1]])

In [15]:
# Task 8.2

def cofactor(A):
    co = minor(A)
    for i in range(len(A)):
        for j in range(len(A)):
            co[i][j] = (-1)**(i+j) * co[i][j]
        # end for
    # end for
    return co
# end func

print('the cofactor of D is')
cofactor(D)

the cofactor of D is


array([[ 1,  0,  0,  0],
       [-1,  1,  2, -1],
       [ 3, -1,  2,  0],
       [-1,  0, -3,  1]])

In [16]:
# Task 8.3

def adjoint(A):
    return transpose(cofactor(A))
# end func

print('the adjoint of D is')
adjoint(D)

the adjoint of D is


array([[ 1, -1,  3, -1],
       [ 0,  1, -1,  0],
       [ 0,  2,  2, -3],
       [ 0, -1,  0,  1]])

In [17]:
# Task 8.4
def inverse(A):
    inver = []
    ad = adjoint(A)
    det = deter(A)
    for i in range(len(A)):
        check = []
        for j in range(len(A)):
            check.append(ad[i][j]/det)
        # end for
        inver.append(check)
    # end for
    return np.array(inver)

print('the inverse of D is')
inverse(D)

the inverse of D is


array([[ 1., -1.,  3., -1.],
       [ 0.,  1., -1.,  0.],
       [ 0.,  2.,  2., -3.],
       [ 0., -1.,  0.,  1.]])