In [1]:
# Exercise 1

import scipy
from scipy.cluster.vq import kmeans,vq,whiten
# Score of 20 students in on subjects
student_scores = [[80], [78], [55], [60], [62],
                  [59], [48], [49], [51], [54],
                  [72], [95], [78], [54], [50],
                  [61], [57], [56], [65], [53]];

In [2]:
# Exercise 2

student_scores = whiten(student_scores)
centroids,_ = kmeans(student_scores,2)

print(student_scores)

print(centroids)

[[6.53573177]
 [6.37233848]
 [4.49331559]
 [4.90179883]
 [5.06519213]
 [4.82010218]
 [3.92143906]
 [4.00313571]
 [4.16652901]
 [4.41161895]
 [5.8821586 ]
 [7.76118148]
 [6.37233848]
 [4.41161895]
 [4.08483236]
 [4.98349548]
 [4.65670889]
 [4.57501224]
 [5.31028207]
 [4.3299223 ]]
[[6.58474976]
 [4.54233358]]


In [3]:
# Exercise 3

result,_ = vq(student_scores, centroids)

print(result)

[0 0 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1]


- try to find center(centroid) of this data form whiten process which is each feature is divided by its standard deviation across all observations to give it unit variance.

In [4]:
# Exercise 4

student_scores = whiten(student_scores)
centroids,_ = kmeans(student_scores,4)
result,_ = vq(student_scores, centroids)
print(student_scores)
print(centroids)
print(result)

[[6.53573177]
 [6.37233848]
 [4.49331559]
 [4.90179883]
 [5.06519213]
 [4.82010218]
 [3.92143906]
 [4.00313571]
 [4.16652901]
 [4.41161895]
 [5.8821586 ]
 [7.76118148]
 [6.37233848]
 [4.41161895]
 [4.08483236]
 [4.98349548]
 [4.65670889]
 [4.57501224]
 [5.31028207]
 [4.3299223 ]]
[[4.22780149]
 [7.76118148]
 [4.90179883]
 [6.29064183]]
[3 3 0 2 2 2 0 0 0 0 3 1 3 0 0 2 2 2 2 0]


In [6]:
# Exercise 5

student_scores = [[80 , 72] , [78 , 56] , [55 , 64] , [60 , 61] , [62 , 45] ,
                  [59 , 71] , [48 , 85] , [49 , 45] , [51 , 55] , [54 , 62] ,
                  [72 , 81] , [95 , 81] , [78 , 92] , [54 , 80] , [50 , 50] ,
                  [61 , 65] , [57 , 62] , [56 , 55] , [65 , 63] , [53 , 72]];

student_scores = whiten(student_scores)
centroids,_ = kmeans(student_scores,4)
result,_ = vq(student_scores, centroids)
print(student_scores)
print(centroids)
print(result)

[[6.53573177 5.57942592]
 [6.37233848 4.33955349]
 [4.49331559 4.9594897 ]
 [4.90179883 4.72701362]
 [5.06519213 3.4871412 ]
 [4.82010218 5.50193389]
 [3.92143906 6.58682226]
 [4.00313571 3.4871412 ]
 [4.16652901 4.26206146]
 [4.41161895 4.80450565]
 [5.8821586  6.27685415]
 [7.76118148 6.27685415]
 [6.37233848 7.12926645]
 [4.41161895 6.19936213]
 [4.08483236 3.87460133]
 [4.98349548 5.03698173]
 [4.65670889 4.80450565]
 [4.57501224 4.26206146]
 [5.31028207 4.88199768]
 [4.3299223  5.57942592]]
[[6.58474976 5.92039083]
 [4.79676028 4.9594897 ]
 [4.37894029 3.87460133]
 [4.22099344 6.1218701 ]]
[0 0 1 1 2 1 3 2 2 1 0 0 0 3 2 1 1 2 1 3]


- whiten the following data and sperate to 4 group of kmean and assign the code of the closet centroid

In [9]:
# Exercise 6

import scipy.constants

print ("The PI is %.16f"% scipy.constants.pi)
print ("The speed of light is c = %.1F"% scipy.constants.c)
print ("The newton ’s gravity constant is G = %.1F"% scipy.constants.g)

The PI is 3.1415926535897931
The speed of light is c = 299792458.0
The newton ’s gravity constant is G = 9.8


In [11]:
# Exercise 7

scipy.constants.find("gram")

['atomic mass unit-kilogram relationship',
 'electron volt-kilogram relationship',
 'hartree-kilogram relationship',
 'hertz-kilogram relationship',
 'inverse meter-kilogram relationship',
 'joule-kilogram relationship',
 'kelvin-kilogram relationship',
 'kilogram-atomic mass unit relationship',
 'kilogram-electron volt relationship',
 'kilogram-hartree relationship',
 'kilogram-hertz relationship',
 'kilogram-inverse meter relationship',
 'kilogram-joule relationship',
 'kilogram-kelvin relationship']

- .find : find the key(in " ") in the previous data

In [13]:
# Exercise 8

print(scipy.constants.physical_constants["atomic mass unit-kilogram relationship"])

(1.6605390666e-27, 'kg', 5e-37)


In [20]:
# Exercise 9

import scipy.constants

m = 55
c = scipy.constants.c
energy = m*(c**2)
print(energy)

4.943153483052497e+18


In [16]:
# Exercise 10

from scipy import stats
import numpy as np

x = np.array([19 ,18 ,21 ,16 ,15 ,17 ,20 ,18]);
print(stats.tmin(x), stats.tmax(x), stats.tmean(x), stats.tvar(x));

15 21 18.0 4.0


In [17]:
# Exercise 11

print(stats.describe(x));

DescribeResult(nobs=8, minmax=(15, 21), mean=18.0, variance=4.0, skewness=0.0, kurtosis=-1.0)


- Compute several descriptive statistics of the passed array.

In [18]:
# Exercise 12

from scipy import stats
import numpy as np

student_scores = [[80] , [78] , [55] , [60] , [62] ,
                  [59] , [48] , [49] , [51] , [54] ,
                  [72] , [95] , [78] , [54] , [50] ,
                  [61] , [57] , [56] , [65] , [53]];

print(stats.tmean(student_scores))
print(stats.tstd(student_scores))
print((62 - stats.tmean(student_scores)) / stats.tstd(student_scores))

61.85
[12.55838994]
[0.01194421]


- find trimmed mean of the array elements

- find trimmed standard deviation of the array elements

- to calculate z-score from mentioned data minus trimmed mean of the array elements divided by trimmed standard deviation of the array elements

In [21]:
# Exercise 13

from scipy import stats
import numpy as np

for i in range(len(student_scores)):
    z = (student_scores[i] - stats.tmean(student_scores)) / stats.tstd(student_scores)
    print('z-scores of {} is {}'.format(student_scores[i],z))
# end for

z-scores of [80] is [1.44524896]
z-scores of [78] is [1.28599288]
z-scores of [55] is [-0.54545209]
z-scores of [60] is [-0.14731188]
z-scores of [62] is [0.01194421]
z-scores of [59] is [-0.22693992]
z-scores of [48] is [-1.10284838]
z-scores of [49] is [-1.02322034]
z-scores of [51] is [-0.86396425]
z-scores of [54] is [-0.62508013]
z-scores of [72] is [0.80822462]
z-scores of [95] is [2.63966959]
z-scores of [78] is [1.28599288]
z-scores of [54] is [-0.62508013]
z-scores of [50] is [-0.9435923]
z-scores of [61] is [-0.06768384]
z-scores of [57] is [-0.386196]
z-scores of [56] is [-0.46582404]
z-scores of [65] is [0.25082833]
z-scores of [53] is [-0.70470817]
